# Jekyll configuration for GitHub Pages
theme: jekyll-theme-minimal
title: Zoom Memo Automation
description: Automated Zoom meeting transcription and summary system with Slack integration

# Exclude files and directories from Jekyll build
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
  - .env.example
  - .gitignore
  - 1.src/
  - 2.tests/
  - 3.operations/
  - recordings/
  - tmp/
  - vercel.json
  - .github/

# Include only documentation
include:
  - 0.docs/

# GitHub Pages source directory
source: ./

# Output directory
destination: ./_site

# Base URL for GitHub Pages
baseurl: /zoom-memo-automation

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag