# Jekyll configuration for GitHub Pages
theme: jekyll-theme-minimal
title: Zoom Memo Automation
description: Automated Zoom meeting transcription and summary system with Slack integration

# Exclude files and directories from Jekyll build
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
  - .env.example
  - .gitignore
  - 1.src/
  - 2.tests/
  - 3.operations/
  - recordings/
  - tmp/
  - vercel.json
  - .github/
  - .vercel/

# Include documentation directory
include:
  - 0.docs/

# Base URL for GitHub Pages
baseurl: /zoom-memo-automation

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag