# Jekyll configuration for GitHub Pages
theme: jekyll-theme-minimal
title: Zoom Memo Automation
description: Automated Zoom meeting transcription and summary system with Slack integration

# Disable Jekyll features that cause build errors
sass:
  style: compressed
  
# Base URL for GitHub Pages
baseurl: /zoom-memo-automation

# Minimal plugins
plugins:
  - jekyll-seo-tag